name: PR

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    timeout-minutes: 60
    name: Unit & E2E Tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit and e2e tests
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run test
      - run: bun run e2e-ci
      - run: bunx prettier -c "'lib/**/*.ts' 'index.ts' 'integration/**/*.ts'"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
